# Generated by Django 5.0.3 on 2024-03-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_tasks_delete_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
